import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // --- New Battle Tab Styles ---
  crownChestBar: {
    width: '95%',
    height: 45,
    backgroundColor: '#34495e',
    borderRadius: 22.5,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
    marginTop: 10,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#2c3e50',
    elevation: 5,
  },
  passRoyaleIcon: {
    width: 35,
    height: 35,
    backgroundColor: '#f1c40f',
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  crownProgressContainer: {
    flex: 1,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  crownProgressBar: {
    width: '100%',
    height: 12,
    backgroundColor: '#1a1a1a',
    borderRadius: 6,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#444',
  },
  crownProgressFill: {
    height: '100%',
    backgroundColor: '#f1c40f',
  },
  crownProgressText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    marginTop: 2,
  },
  crownChestReward: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arenaMainView: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trophyRoadContainer: {
    width: '80%',
    height: 20,
    marginTop: 10,
  },
  trophyRoadTrack: {
    width: '100%',
    height: 8,
    backgroundColor: '#2c3e50',
    borderRadius: 4,
    position: 'relative',
  },
  trophyRoadFill: {
    height: '100%',
    backgroundColor: '#3498db',
    borderRadius: 4,
  },
  trophyMarker: {
    position: 'absolute',
    top: -15,
    alignItems: 'center',
  },
  trophyMarkerText: {
    color: '#f1c40f',
    fontSize: 10,
    fontWeight: 'bold',
  },
  arenaVisualContainer: {
    marginVertical: 20,
    elevation: 10,
  },
  battleActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 15,
    marginBottom: 20,
  },
  smallBlueButton: {
    width: 50,
    height: 50,
    backgroundColor: '#3498db',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#2980b9',
    borderBottomWidth: 5,
    borderBottomColor: '#1f618d',
    justifyContent: 'center',
    alignItems: 'center',
  },
  smallButtonIcon: {
    fontSize: 24,
  },
  battleButtonTrophyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: -5,
  },
  battleButtonTrophyText: {
    color: '#5D4037',
    fontSize: 12,
    fontWeight: 'bold',
    marginRight: 2,
  },

  // --- New Deck Tab Styles ---
  deckGridContainer: {
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderRadius: 15,
    padding: 10,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#f1c40f',
  },
  deckSelectorMini: {
    flexDirection: 'row',
    gap: 5,
  },
  deckDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#555',
  },
  deckDotActive: {
    backgroundColor: '#f1c40f',
  },
  deckCardGrid: {
    marginVertical: 10,
  },
  cardRowCompact: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  deckCardCompact: {
    width: '23%',
    aspectRatio: 0.8,
    backgroundColor: '#fff',
    borderRadius: 5,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  cardCostSmall: {
    position: 'absolute',
    top: -5,
    left: -5,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#D442F5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#fff',
  },
  cardCostSmallText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  deckFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 5,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  towerTroopSlot: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  towerTroopText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  avgElixirText: {
    color: '#f1c40f',
    fontSize: 12,
    fontWeight: 'bold',
  },
  collectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  collectionTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  filterButtonMini: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#34495e',
    borderRadius: 5,
  },
  searchContainer: {
    flexDirection: 'row',
    backgroundColor: '#2c3e50',
    borderRadius: 8,
    marginBottom: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#34495e',
  },
  searchInput: {
    flex: 1,
    padding: 10,
    color: '#fff',
    fontSize: 14,
    minHeight: 40,
  },
  searchClearButton: {
    padding: 8,
    marginRight: 5,
  },
  searchClearButtonText: {
    color: '#999',
    fontSize: 16,
    fontWeight: 'bold',
  },

  // --- New Shop Styles ---
  specialOfferBanner: {
    width: '100%',
    height: 180,
    borderRadius: 15,
    overflow: 'hidden',
    marginBottom: 20,
    elevation: 8,
  },
  specialOfferGradient: {
    flex: 1,
    padding: 15,
  },
  offerTag: {
    backgroundColor: '#e74c3c',
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 5,
    alignSelf: 'flex-start',
    marginBottom: 5,
  },
  offerTitle: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '900',
    textShadowColor: 'black',
    textShadowRadius: 2,
  },
  offerImageRow: {
    flexDirection: 'row',
    gap: 20,
    marginVertical: 15,
  },
  offerButton: {
    backgroundColor: '#2ecc71',
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 20,
    alignSelf: 'center',
    borderBottomWidth: 4,
    borderBottomColor: '#27ae60',
  },
  offerButtonText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 18,
  },
  dealRarityBar: {
    width: '100%',
    height: 4,
    position: 'absolute',
    top: 0,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
  },
  chestShopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  shopChestCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
    elevation: 5,
  },
  shopChestName: {
    fontWeight: 'bold',
    marginVertical: 5,
  },
  shopChestPrice: {
    backgroundColor: '#34495e',
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 15,
  },
  shopChestPriceText: {
    color: '#fff',
    fontWeight: 'bold',
  },

  // --- New Social Styles ---
  socialHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 15,
    backgroundColor: '#2c3e50',
    borderBottomWidth: 3,
    borderBottomColor: '#f1c40f',
  },
  clanMainInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  clanBadgeLarge: {
    width: 50,
    height: 55,
    backgroundColor: '#3498db',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  clanNameText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '900',
  },
  clanStatusText: {
    color: '#bdc3c7',
    fontSize: 12,
  },
  requestBanner: {
    backgroundColor: '#27ae60',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  requestText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  requestButton: {
    backgroundColor: '#f1c40f',
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 5,
  },
  requestButtonText: {
    fontWeight: '900',
    fontSize: 12,
  },

  // --- New Events Tab Styles ---
  eventsContainer: {
    flex: 1,
    padding: 10,
  },
  eventCard: {
    width: '100%',
    borderRadius: 15,
    overflow: 'hidden',
    marginBottom: 15,
    elevation: 5,
  },
  eventGradient: {
    padding: 20,
  },
  eventBadge: {
    backgroundColor: '#f1c40f',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 5,
    alignSelf: 'flex-start',
    marginBottom: 10,
  },
  eventBadgeText: {
    fontWeight: '900',
    fontSize: 10,
  },
  eventTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '900',
    textShadowColor: 'black',
    textShadowRadius: 2,
  },
  eventSubtitle: {
    color: '#ccc',
    fontSize: 14,
    marginBottom: 15,
  },
  eventRewards: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 20,
  },
  rewardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(0,0,0,0.3)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
  },
  rewardValue: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },
  eventButton: {
    backgroundColor: '#2ecc71',
    paddingVertical: 12,
    borderRadius: 25,
    alignItems: 'center',
    borderBottomWidth: 4,
    borderBottomColor: '#27ae60',
  },
  eventButtonText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 16,
  },
  eventStatsRow: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 20,
  },
  eventStat: {
    color: '#fff',
    fontWeight: 'bold',
  },

  // --- Existing Styles (Optimized) ---
  container: {
    flex: 1,
    backgroundColor: '#333',
  },
  menuContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuBackgroundImage: {
    resizeMode: 'cover',
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)', // Lighter overlay for better bg visibility
    width: '100%',
    alignItems: 'center',
    paddingVertical: 30,
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 50,
  },
  logoTextClash: {
    fontSize: 50,
    fontWeight: '900',
    color: '#fff',
    textShadowColor: '#000',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 0,
    fontFamily: 'sans-serif-condensed', // Attempt to match font
    marginBottom: -10, // Stack them
  },
  logoTextRoyale: {
    fontSize: 50,
    fontWeight: '900',
    color: '#FFD700', // Gold
    textShadowColor: '#000',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 0,
    fontFamily: 'sans-serif-condensed',
  },
  loadingBottomContainer: {
    width: '90%',
    alignItems: 'center',
    marginBottom: 10,
  },
  tipText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  loadingBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 5,
  },
  loadingPercentage: {
    color: '#D442F5', // Pink/Purple text
    fontSize: 18,
    fontWeight: 'bold',
    marginRight: 10,
    width: 50,
    textAlign: 'right',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  loadingBarTrack: {
    flex: 1,
    height: 16,
    backgroundColor: '#333',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#000',
    overflow: 'hidden',
  },
  loadingBarFill: {
    height: '100%',
    backgroundColor: '#D442F5', // Purple loading bar
  },
  loadingStateText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 2,
  },
  copyrightText: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 10,
    fontWeight: 'bold',
    marginTop: 10,
  },
  // Legacy styles (kept if needed by other components, though mostly replaced)
  headerContainer: {
    alignItems: 'center',
    marginBottom: 80,
  },
  bottomContainer: {
    alignItems: 'center',
    width: '100%',
  },
  title: {
    fontSize: 50,
    fontWeight: '900',
    color: '#FFD700',
    textShadowColor: '#8B4500',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 0,
    marginBottom: 0,
    letterSpacing: 2,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 5,
    marginBottom: 0,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 1,
    textAlign: 'center',
  },
  loadingContainer: {
    width: '80%',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    padding: 25,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  loadingText: {
    color: '#FFD700',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 15,
    textTransform: 'uppercase',
    letterSpacing: 1,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  progressBarBg: {
    width: '100%',
    height: 30,
    backgroundColor: '#333',
    borderRadius: 15,
    borderWidth: 3,
    borderColor: '#BDC3C7', // Silver border
    overflow: 'hidden',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#F39C12', // Orange base
    borderRightWidth: 4,
    borderRightColor: '#F1C40F', // Highlight edge
  },
  battleButton: {
    backgroundColor: '#F1C40F', // Main Gold Color
    paddingVertical: 15,
    paddingHorizontal: 60,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#F39C12', // Darker Gold Border
    borderBottomWidth: 6,
    borderBottomColor: '#C27C0E', // Shadow/3D effect
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 8,
    marginTop: 10,
    alignItems: 'center',
    marginBottom: 20, // Add space at bottom
  },
  battleButtonText: {
    color: '#5D4037', // Dark Brown Text
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: 1,
    textShadowColor: 'rgba(255,255,255,0.4)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 0,
    fontFamily: 'sans-serif-condensed', // Match CR font style
  },
  battleButtonSubtext: {
    color: '#5D4037',
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: -2,
  },
  friendlyButton: {
    backgroundColor: '#3498db',
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#2980b9',
    borderBottomWidth: 4,
    borderBottomColor: '#1f618d',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
    marginBottom: 20,
  },
  friendlyButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  // Friendly Battle Modal
  friendlyModalContent: {
    backgroundColor: '#ecf0f1',
    borderRadius: 20,
    padding: 25,
    width: '90%',
    maxWidth: 350,
    borderWidth: 4,
    borderColor: '#3498db',
    alignItems: 'center',
  },
  friendlyModalTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#2c3e50',
    marginBottom: 20,
    textAlign: 'center',
  },
  roomInput: {
    width: '100%',
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingHorizontal: 15,
    fontSize: 18,
    textAlign: 'center',
    borderWidth: 2,
    borderColor: '#bdc3c7',
    marginBottom: 20,
    color: '#2c3e50',
    fontWeight: 'bold',
  },
  roomButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 10,
  },
  createRoomButton: {
    flex: 1,
    backgroundColor: '#2ecc71',
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: 'center',
    borderBottomWidth: 4,
    borderBottomColor: '#27ae60',
  },
  joinRoomButton: {
    flex: 1,
    backgroundColor: '#3498db',
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: 'center',
    borderBottomWidth: 4,
    borderBottomColor: '#2980b9',
  },
  roomButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  roomCodeText: {
    fontSize: 32,
    fontWeight: '900',
    color: '#3498db',
    marginVertical: 20,
    letterSpacing: 5,
  },
  waitingText: {
    fontSize: 16,
    color: '#7f8c8d',
    marginBottom: 20,
    fontStyle: 'italic',
  },
  footerText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    marginTop: 25,
  },
  gameBoard: {
    flex: 1,
    backgroundColor: '#639c3e', // Better grass green
    position: 'relative',
    overflow: 'hidden',
  },
  river: {
    position: 'absolute',
    top: '50%',
    marginTop: -25,
    height: 50,
    backgroundColor: '#4fa3d1',
    width: '100%',
    borderTopWidth: 4,
    borderBottomWidth: 4,
    borderColor: '#8fb8d6', // Lighter foam edge
    zIndex: 1,
    opacity: 0.9,
  },
  bridge: {
    position: 'absolute',
    width: 60,
    height: 54, // Slightly longer than river to overlap
    top: -2,
    backgroundColor: '#795548', // Wood brown
    borderColor: '#3e2723',
    borderWidth: 2,
    borderRadius: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 3,
  },
  towerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: "#000",
    elevation: 8,
  },
  arrowContainer: {
    position: 'absolute',
    width: 20,
    height: 10,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  arrowShaft: {
    width: 15,
    height: 2,
    backgroundColor: '#8B4513',
    position: 'absolute',
  },
  arrowHead: {
    width: 0,
    height: 0,
    borderTopWidth: 4,
    borderBottomWidth: 4,
    borderLeftWidth: 6,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#A9A9A9',
    position: 'absolute',
    right: 0,
  },
  cannonball: {
    position: 'absolute',
    width: 12,
    height: 12,
    backgroundColor: 'black',
    borderRadius: 6,
    zIndex: 100,
  },
  bullet: {
    position: 'absolute',
    width: 8,
    height: 8,
    backgroundColor: '#2c3e50',
    borderRadius: 4,
    zIndex: 100,
  },
  witchProjectile: {
    position: 'absolute',
    width: 10,
    height: 10,
    backgroundColor: '#9b59b6',
    borderRadius: 5,
    zIndex: 100,
    borderWidth: 1,
    borderColor: '#8e44ad',
    shadowColor: '#9b59b6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 3,
  },
  dragonFire: {
    position: 'absolute',
    width: 16,
    height: 16,
    backgroundColor: '#27ae60',
    borderRadius: 8,
    zIndex: 100,
    borderWidth: 2,
    borderColor: '#2ecc71',
    shadowColor: '#27ae60',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 6,
    elevation: 4,
  },
  fireballSmall: {
    position: 'absolute',
    width: 14,
    height: 14,
    backgroundColor: '#e67e22',
    borderRadius: 7,
    zIndex: 100,
    borderWidth: 1,
    borderColor: '#f1c40f',
  },
  fireballSpell: {
    position: 'absolute',
    width: 30,
    height: 30,
    backgroundColor: '#e74c3c',
    borderRadius: 15,
    zIndex: 100,
    borderWidth: 2,
    borderColor: '#f1c40f',
    shadowColor: 'orange',
    shadowRadius: 10,
    elevation: 10,
  },
  zapSpell: {
    position: 'absolute',
    width: 50,
    height: 50,
    zIndex: 100,
  },
  lightningBolt: {
    width: '100%',
    height: '100%',
    backgroundColor: '#3498db',
    borderRadius: 25,
    opacity: 0.8,
    shadowColor: '#3498db',
    shadowRadius: 15,
    elevation: 15,
  },
  arrowsSpell: {
    position: 'absolute',
    width: 40,
    height: 40,
    zIndex: 100,
  },
  arrowVolley: {
    width: '100%',
    height: '100%',
    backgroundColor: '#2ecc71',
    borderRadius: 20,
    opacity: 0.7,
    shadowColor: '#27ae60',
    shadowRadius: 10,
    elevation: 10,
  },
  poisonSpell: {
    position: 'absolute',
    width: 100,
    height: 100,
    backgroundColor: 'rgba(155, 89, 182, 0.4)',
    borderRadius: 50,
    zIndex: 100,
    borderWidth: 3,
    borderColor: '#9b59b6',
  },
  unit: {
    position: 'absolute',
    width: 30,
    height: 30,
    zIndex: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  healthBarBack: {
    position: 'absolute',
    top: -10,
    width: '120%',
    height: 6,
    backgroundColor: '#333',
    borderRadius: 3,
    borderWidth: 1,
    borderColor: '#000',
    overflow: 'hidden',
  },
  healthBarFront: {
    height: '100%',
  },
  footerContainer: {
    backgroundColor: '#1a1a2e',
    paddingBottom: 8,
    borderTopWidth: 3,
    borderTopColor: '#D442F5',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  deckContainer: {
    flexDirection: 'row',
    padding: 5,
    alignItems: 'flex-end',
    height: 90,
  },
  nextCardContainer: {
    width: 50,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  handContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  card: {
    width: 60,
    height: 75,
    backgroundColor: '#ecf0f1',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#2c3e50',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  cardContent: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  hiddenCard: {
    opacity: 0.3,
  },
  nextCard: {
    width: 40,
    height: 50,
    opacity: 0.8,
  },
  disabledCard: {
    opacity: 0.5,
  },
  cardName: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#000',
    textAlign: 'center',
    marginTop: 2,
  },
  elixirCostBubble: {
    position: 'absolute',
    top: -6,
    left: -6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#D442F5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    zIndex: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
  },
  elixirCostText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 10,
  },
  nextLabel: {
    position: 'absolute',
    top: -15,
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  elixirSection: {
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  elixirContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  elixirText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    marginRight: 10,
    width: 25,
    textAlign: 'center',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  elixirBarBack: {
    flex: 1,
    height: 20,
    backgroundColor: '#1a1a2e',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#0f0f1a',
    overflow: 'hidden',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  elixirBarFill: {
    height: '100%',
    backgroundColor: '#D442F5',
    borderRadius: 8,
  },
  elixirTick: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  debugBtnSmall: {
    backgroundColor: '#555',
    padding: 5,
    borderRadius: 4,
    marginLeft: 10,
  },
  dragProxy: {
    position: 'absolute',
    width: 60,
    height: 75,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
    elevation: 20,
  },
  dragProxyLabel: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 5,
    borderRadius: 4,
    marginTop: 5,
  },
  timerContainer: {
    position: 'absolute',
    top: 10,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.75)',
    padding: 8,
    paddingHorizontal: 15,
    borderRadius: 8,
    zIndex: 50,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  timerText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 20,
    letterSpacing: 1,
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  gameOverContainer: {
    position: 'absolute',
    top: 0, bottom: 0, left: 0, right: 0,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  gameOverTitle: {
    fontSize: 52,
    fontWeight: '900',
    marginBottom: 30,
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 8,
    letterSpacing: 2,
  },
  restartButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 18,
    paddingHorizontal: 40,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 8,
  },
  restartButtonText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 1,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  // Lobby Styles
  lobbyContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  lobbyOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  tabContentArea: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 0,
  },
  bottomNavigation: {
    height: 75,
    backgroundColor: '#1a1a2e',
    flexDirection: 'row',
    borderTopWidth: 2,
    borderTopColor: '#D442F5',
    paddingBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 15,
  },
  tabButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
  },
  tabButtonActive: {
    borderTopWidth: 4,
    borderTopColor: '#D442F5',
  },
  tabIcon: {
    fontSize: 26,
    marginBottom: 4,
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#888',
    letterSpacing: 0.5,
  },
  tabLabelActive: {
    color: '#D442F5',
    fontWeight: '900',
  },
  placeholderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderTitle: {
    fontSize: 36,
    fontWeight: '900',
    color: '#F1C40F',
    marginBottom: 10,
  },
  placeholderText: {
    fontSize: 18,
    color: '#888',
  },
  battleTabContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  deckPreviewTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#F1C40F',
    marginBottom: 20,
  },
  deckPreview: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 30,
  },
  miniCard: {
    width: 70,
    height: 90,
    backgroundColor: '#fff',
    borderRadius: 8,
    margin: 5,
    borderWidth: 3,
    // borderColor set dynamically
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
  },
  miniCardName: {
    fontSize: 10,
    fontWeight: 'bold',
    marginTop: 5,
  },
  miniCardCost: {
    position: 'absolute',
    top: -5,
    right: -5,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#D442F5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#fff',
  },
  miniCardCostText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },
  // --- Deck Tab Styles ---
  deckTabContainer: {
    flex: 1,
    paddingHorizontal: 15,
    paddingTop: 15,
  },
  deckHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 5,
  },
  deckTabTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#fff',
    textShadowColor: 'black',
    textShadowRadius: 2,
  },
  magicItemsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#3498db',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#2980b9',
  },
  magicItemIcon: {
    marginRight: 5,
  },
  magicItemsText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },
  deckStatsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  deckStatItem: {
    alignItems: 'center',
  },
  deckStatLabel: {
    color: '#ccc',
    fontSize: 10,
    marginBottom: 2,
    fontWeight: '600',
  },
  deckStatValue: {
    color: '#D442F5',
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  deckStatDivider: {
    width: 1,
    height: '80%',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  deckSelectorContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#3498db',
  },
  deckSelectorLabel: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    textShadowColor: 'black',
    textShadowRadius: 2,
  },
  deckSelectorButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  deckSelectorButton: {
    flex: 1,
    backgroundColor: 'rgba(52, 152, 219, 0.4)',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#2980b9',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 50,
  },
  deckSelectorButtonActive: {
    backgroundColor: '#2980b9',
    borderColor: '#f1c40f',
    shadowColor: '#f1c40f',
    shadowRadius: 8,
    elevation: 8,
    transform: [{ scale: 1.05 }],
  },
  deckSelectorButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  deckSelectorButtonTextActive: {
    color: '#f1c40f',
    fontSize: 17,
    textShadowColor: 'rgba(241, 196, 15, 0.5)',
    textShadowRadius: 4,
  },
  filterContainer: {
    paddingHorizontal: 5,
    marginBottom: 5,
  },
  filterButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#bdc3c7',
    marginRight: 8,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  filterButtonActive: {
    backgroundColor: '#34495e',
    borderColor: '#fff',
  },
  filterButtonText: {
    color: '#bdc3c7',
    fontSize: 12,
    fontWeight: 'bold',
  },
  filterButtonTextActive: {
    color: '#fff',
  },
  deckBox: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderWidth: 3,
    borderColor: '#F1C40F',
    borderRadius: 12,
    marginBottom: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  deckBoxTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F1C40F',
    marginBottom: 8,
    textAlign: 'center',
  },
  deckBoxInner: {
    alignItems: 'center',
  },
  allCardsScroll: {
    flex: 1,
    marginBottom: 80,
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginBottom: 10,
  },
  deckCard: {
    width: 70,
    height: 85,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#F1C40F',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginHorizontal: 3,
  },
  deckCardBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: 'rgba(46, 204, 113, 0.9)',
    borderRadius: 10,
    width: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#27ae60',
  },
  deckCardBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  deckCardHighlight: {
    backgroundColor: 'rgba(241, 196, 15, 0.4)',
    borderWidth: 3,
    transform: [{ scale: 1.05 }],
  },
  draggableCard: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 2,
  },
  dragHandle: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 3,
    paddingHorizontal: 3,
    paddingVertical: 1,
  },
  dragHandleIcon: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: -2,
  },
  deckCardSelected: {
    backgroundColor: 'rgba(46, 204, 113, 0.3)',
    borderWidth: 3,
    shadowColor: '#2ecc71',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 5,
  },
  selectedBadge: {
    position: 'absolute',
    top: -8,
    left: -8,
    backgroundColor: '#2ecc71',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
  },
  selectedBadgeText: {
    color: '#fff',
    fontSize: 8,
    fontWeight: '900',
  },
  swapInstructions: {
    backgroundColor: 'rgba(46, 204, 113, 0.2)',
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginBottom: 10,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2ecc71',
  },
  swapInstructionsText: {
    color: '#2ecc71',
    fontSize: 12,
    fontWeight: 'bold',
    flex: 1,
  },
  cancelButton: {
    color: '#e74c3c',
    fontSize: 12,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  deckCardName: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 3,
  },
  deckCardCost: {
    position: 'absolute',
    top: -5,
    right: -5,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#D442F5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  deckCardCostText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 11,
  },
  cardTypeBadge: {
    position: 'absolute',
    bottom: 2,
    backgroundColor: '#ff4500',
    paddingHorizontal: 3,
    paddingVertical: 1,
    borderRadius: 3,
  },
  cardTypeBadgeFlying: {
    position: 'absolute',
    bottom: 2,
    backgroundColor: '#27ae60',
    paddingHorizontal: 3,
    paddingVertical: 1,
    borderRadius: 3,
  },
  cardTypeBadgeBuilding: {
    position: 'absolute',
    bottom: 2,
    backgroundColor: '#8B4513',
    paddingHorizontal: 3,
    paddingVertical: 1,
    borderRadius: 3,
  },
  cardTypeText: {
    color: '#fff',
    fontSize: 6,
    fontWeight: '900',
  },
  // Card Detail Modal Styles
  cardDetailModal: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  cardDetailModalContent: {
    backgroundColor: '#2c3e50',
    borderRadius: 20,
    padding: 25,
    width: '90%',
    maxWidth: 350,
    borderWidth: 4,
    borderColor: '#ecf0f1',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 25,
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 35,
    height: 35,
    borderRadius: 17,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#e74c3c',
    fontSize: 20,
    fontWeight: 'bold',
  },
  cardDetailHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  cardDetailIconBig: {
    width: 120,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginBottom: 10,
  },
  cardDetailCostBig: {
    position: 'absolute',
    top: 10,
    left: 10,
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#D442F5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#fff',
    zIndex: 10,
  },
  cardDetailCostBigText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 20,
  },
  cardDetailNameBig: {
    fontSize: 28,
    fontWeight: '900',
    color: '#F1C40F',
    marginBottom: 8,
    textAlign: 'center',
  },
  cardDetailTypeBig: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#ff4500',
    backgroundColor: 'rgba(255, 69, 0, 0.2)',
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 15,
  },
  cardDetailTypeBigFlying: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#27ae60',
    backgroundColor: 'rgba(39, 174, 96, 0.2)',
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 15,
  },
  cardDetailTypeBigBuilding: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#8B4513',
    backgroundColor: 'rgba(139, 69, 19, 0.2)',
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 15,
  },
  cardDetailStatsBig: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  statLabel: {
    fontSize: 14,
    color: '#aaa',
    fontWeight: '600',
  },
  statValue: {
    fontSize: 14,
    color: '#fff',
    fontWeight: 'bold',
  },
  upgradeButton: {
    backgroundColor: '#F1C40F',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
    alignSelf: 'center',
  },
  upgradeButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '900',
  },
  // --- New Battle Screen Styles ---
  topInfoBar: {
    position: 'absolute',
    top: 10,
    left: 10,
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  bottomInfoBar: {
    position: 'absolute',
    bottom: 145, // Just above the footer
    left: 10,
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  playerInfoContainer: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
    marginRight: 10,
  },
  playerName: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
    textShadowColor: 'black',
    textShadowRadius: 2,
  },
  clanName: {
    color: '#ccc',
    fontSize: 10,
    fontStyle: 'italic',
  },
  trophyContainer: {
    backgroundColor: 'rgba(241, 196, 15, 0.2)',
    padding: 5,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#F1C40F',
  },
  trophyText: {
    color: '#F1C40F',
    fontWeight: 'bold',
    fontSize: 12,
  },
  scoreBoard: {
    position: 'absolute',
    top: 5,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 15,
  },
  crownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 15,
  },
  crownIcon: {
    fontSize: 18,
    marginHorizontal: 2,
  },
  scoreText: {
    fontSize: 24,
    fontWeight: '900',
    color: '#fff',
    textShadowColor: 'black',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  settingsButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 35,
    height: 35,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    zIndex: 60,
  },
  emoteButton: {
    position: 'absolute',
    bottom: 145,
    left: 10,
    width: 40,
    height: 40,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    zIndex: 60,
    display: 'none', // Hidden for now as it overlaps with player info, or we can move it
  },
  timerTextRed: {
    color: '#e74c3c',
  },
  elixirBubble: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    backgroundColor: '#D442F5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    marginRight: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
    elevation: 5,
    zIndex: 10,
  },
  elixirBubbleDouble: {
    backgroundColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 8,
  },
  elixirDoubleText: {
    position: 'absolute',
    bottom: -2,
    fontSize: 10,
    fontWeight: '900',
    color: '#fff',
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
  elixirBarFillDouble: {
    backgroundColor: '#FFD700',
  },
  // --- Double Elixir Alert Styles ---
  doubleElixirAlert: {
    position: 'absolute',
    top: 100,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
  },
  doubleElixirAlertContent: {
    backgroundColor: 'rgba(255, 215, 0, 0.95)',
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 15,
    borderWidth: 3,
    borderColor: '#FFA500',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 10,
    alignItems: 'center',
  },
  doubleElixirAlertTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: '#8B4500',
    textShadowColor: '#FFA500',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
    marginBottom: 5,
  },
  doubleElixirAlertSubtitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#8B4500',
  },
  // --- Lobby Header Styles ---
  lobbyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 45,
    paddingHorizontal: 15,
    paddingBottom: 15,
    backgroundColor: 'rgba(20, 20, 35, 0.95)',
    borderBottomWidth: 3,
    borderBottomColor: '#D442F5',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 10,
  },
  lobbyHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  xpLevelContainer: {
    width: 38,
    height: 38,
    backgroundColor: '#667eea',
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ rotate: '45deg' }],
    borderWidth: 2,
    borderColor: '#9b59b6',
    marginRight: 12,
    shadowColor: '#9b59b6',
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  xpLevelText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 15,
    transform: [{ rotate: '-45deg' }],
  },
  playerIdentity: {
    justifyContent: 'center',
  },
  lobbyPlayerName: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 17,
    marginBottom: 3,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    letterSpacing: 0.5,
  },
  xpBarContainer: {
    width: 85,
    height: 9,
    backgroundColor: '#2c3e50',
    borderRadius: 5,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  xpBarFill: {
    width: '70%',
    height: '100%',
    backgroundColor: '#667eea',
  },
  lobbyHeaderRight: {
    flexDirection: 'row',
  },
  currencyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginLeft: 10,
    borderWidth: 2,
    borderColor: 'rgba(212, 66, 245, 0.5)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
  },
  currencyIcon: {
    fontSize: 13,
    marginRight: 6,
  },
  currencyText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },
  // --- Chest Slots Styles ---
  chestSlotsContainer: {
    width: '100%',
    marginTop: 20,
    paddingHorizontal: 10,
  },
  chestSlotsTitle: {
    color: '#ccc',
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 8,
    textAlign: 'center',
    letterSpacing: 1,
  },
  chestRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  chestSlot: {
    width: '23%',
    height: 60,
    backgroundColor: '#5D4037', // Brown
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#8D6E63',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  chestSlotEmpty: {
    width: '23%',
    height: 60,
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.1)',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  chestText: {
    color: '#FFD700',
    fontWeight: 'bold',
    fontSize: 10,
    marginBottom: 2,
  },
  chestTimer: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 4,
    borderRadius: 3,
  },
  chestTextEmpty: {
    color: '#777',
    fontSize: 9,
    textAlign: 'center',
  },
  // --- Arena Title Styles ---
  arenaTitleContainer: {
    alignItems: 'center',
    marginBottom: 10,
  },
  arenaTitle: {
    color: '#F1C40F',
    fontSize: 24,
    fontWeight: '900',
    textShadowColor: 'black',
    textShadowRadius: 2,
  },
  arenaSubtitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    opacity: 0.8,
  },
  battleButtonSubtext: {
    color: 'rgba(0,0,0,0.5)',
    fontSize: 10,
    fontWeight: 'bold',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  // --- Shop Styles ---
  shopContainer: {
    flex: 1,
    padding: 10,
  },
  shopSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 10,
    marginTop: 10,
    paddingHorizontal: 5,
  },
  shopSectionTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
    textShadowColor: 'black',
    textShadowRadius: 2,
  },
  shopSectionTimer: {
    color: '#f1c40f',
    fontSize: 12,
    fontWeight: 'bold',
  },
  dealsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  dealCard: {
    width: '32%',
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 5,
    marginBottom: 10,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#bdc3c7',
  },
  dealHeader: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#7f8c8d',
    marginBottom: 5,
  },
  dealImageContainer: {
    marginVertical: 5,
    alignItems: 'center',
  },
  dealCount: {
    position: 'absolute',
    bottom: 0,
    right: -5,
    backgroundColor: 'rgba(0,0,0,0.7)',
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    paddingHorizontal: 3,
    borderRadius: 3,
  },
  dealName: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 5,
    height: 25,
  },
  buyButton: {
    backgroundColor: '#2ecc71',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 4,
    width: '100%',
    alignItems: 'center',
    borderBottomWidth: 3,
    borderBottomColor: '#27ae60',
  },
  buyButtonFree: {
    backgroundColor: '#f1c40f',
    borderBottomColor: '#f39c12',
  },
  buyButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 10,
  },
  passBanner: {
    backgroundColor: '#f1c40f',
    borderRadius: 10,
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#f39c12',
  },
  passBannerLeft: {
    flex: 1,
  },
  passBannerTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 10,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowRadius: 2,
  },
  passButton: {
    backgroundColor: '#fff',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  passButtonText: {
    color: '#f1c40f',
    fontWeight: 'bold',
    fontSize: 12,
  },

  // --- Clan Styles ---
  clanTabContainer: {
    flex: 1,
  },
  clanHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: 'rgba(0,0,0,0.4)',
    marginBottom: 5,
  },
  clanHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  clanBadge: {
    width: 40,
    height: 45,
    backgroundColor: '#3498db',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#2980b9',
  },
  clanName: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    textShadowColor: 'black',
    textShadowRadius: 2,
  },
  clanStats: {
    color: '#ccc',
    fontSize: 12,
  },
  clanInfoButton: {
    width: 25,
    height: 25,
    borderRadius: 12.5,
    backgroundColor: '#3498db',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#fff',
  },
  chatContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  chatList: {
    flex: 1,
  },
  chatRow: {
    flexDirection: 'row',
    marginBottom: 10,
    alignItems: 'flex-end',
  },
  chatRowMe: {
    justifyContent: 'flex-end',
  },
  chatRowOther: {
    justifyContent: 'flex-start',
  },
  chatAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#555',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
  },
  chatBubble: {
    padding: 10,
    borderRadius: 10,
    maxWidth: '80%',
  },
  chatBubbleMe: {
    backgroundColor: '#3498db',
    borderBottomRightRadius: 0,
  },
  chatBubbleOther: {
    backgroundColor: '#fff',
    borderBottomLeftRadius: 0,
  },
  chatUser: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#e67e22',
    marginBottom: 2,
  },
  chatRole: {
    color: '#999',
    fontWeight: 'normal',
  },
  chatText: {
    color: '#333', // Default text color
    fontSize: 14,
  },
  chatTime: {
    fontSize: 8,
    color: 'rgba(0,0,0,0.5)',
    alignSelf: 'flex-end',
    marginTop: 2,
  },
  systemMessage: {
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 10,
    marginBottom: 10,
  },
  systemMessageText: {
    color: '#ccc',
    fontSize: 10,
    fontStyle: 'italic',
  },
  inputContainer: {
    flexDirection: 'row',
    padding: 10,
    backgroundColor: '#2c3e50',
    alignItems: 'center',
  },
  chatInput: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    height: 40,
  },
  sendButton: {
    backgroundColor: '#f1c40f',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
  },
  sendButtonText: {
    color: '#333',
    fontWeight: 'bold',
  },
  // --- Card Menu Styles ---
  cardMenuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  cardMenuContent: {
    backgroundColor: '#1a1a2e',
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 320,
    borderWidth: 3,
    borderColor: '#F1C40F',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 10,
  },
  cardMenuPreview: {
    alignItems: 'center',
    marginBottom: 15,
    position: 'relative',
  },
  cardMenuIconWrapper: {
    width: 80,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    marginBottom: 10,
  },
  cardMenuIcon: {
    fontSize: 50,
  },
  cardMenuCostBadge: {
    position: 'absolute',
    top: -5,
    left: -5,
    width: 35,
    height: 35,
    borderRadius: 17.5,
    backgroundColor: '#D442F5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    zIndex: 10,
  },
  cardMenuCostText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 16,
  },
  cardMenuName: {
    fontSize: 20,
    fontWeight: '900',
    color: '#F1C40F',
    textAlign: 'center',
    marginBottom: 5,
  },
  cardMenuRarityBadge: {
    backgroundColor: '#f39c12',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
    marginTop: 5,
  },
  cardMenuRarityText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  cardMenuStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    padding: 10,
    marginBottom: 15,
  },
  cardMenuStat: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  cardMenuStatLabel: {
    color: '#aaa',
    fontSize: 10,
    marginBottom: 2,
    fontWeight: '600',
  },
  cardMenuStatValue: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  cardMenuButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  cardMenuButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardMenuButtonInfo: {
    backgroundColor: '#3498db',
    borderBottomWidth: 3,
    borderBottomColor: '#2980b9',
  },
  cardMenuButtonSwap: {
    backgroundColor: '#2ecc71',
    borderBottomWidth: 3,
    borderBottomColor: '#27ae60',
  },
  cardMenuButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '900',
  },
  cardMenuOr: {
    color: '#aaa',
    fontSize: 12,
    textAlign: 'center',
    marginVertical: 10,
    fontStyle: 'italic',
  },
  cardMenuCancel: {
    marginTop: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  cardMenuCancelText: {
    color: '#e74c3c',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // --- Deck Slot Selector Styles ---
  deckSelectorContainer: {
    width: '100%',
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  deckSelectorLabel: {
    color: '#ccc',
    fontSize: 10,
    fontWeight: 'bold',
    marginBottom: 5,
    letterSpacing: 1,
  },
  deckSelectorButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 8,
    padding: 3,
  },
  deckSelectorButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 6,
  },
  deckSelectorButtonActive: {
    backgroundColor: '#F1C40F',
  },
  deckSelectorButtonText: {
    color: '#aaa',
    fontSize: 12,
    fontWeight: 'bold',
  },
  deckSelectorButtonTextActive: {
    color: '#000',
  },
  slotSelectorContent: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  slotSelectorTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 20,
    textAlign: 'center',
  },
  slotSelectorDeck: {
    width: '100%',
    maxWidth: 350,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 15,
    padding: 12,
    borderWidth: 2,
    borderColor: '#F1C40F',
  },
  slotSelectorSlotRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 8,
  },
  slotSelectorSlot: {
    width: 70,
    height: 85,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#F1C40F',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  slotSelectorSlotHighlighted: {
    backgroundColor: 'rgba(46, 204, 113, 0.3)',
    borderWidth: 3,
    shadowColor: '#2ecc71',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 5,
  },
  slotSelectorSlotIcon: {
    fontSize: 40,
    marginBottom: 5,
  },
  slotSelectorSlotName: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 3,
    textAlign: 'center',
  },
  slotSelectorSlotCost: {
    position: 'absolute',
    top: -5,
    right: -5,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#D442F5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  slotSelectorSlotCostText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 11,
  },
  slotSelectorCancel: {
    marginTop: 20,
    paddingVertical: 12,
    paddingHorizontal: 30,
    backgroundColor: '#e74c3c',
    borderRadius: 25,
  },
  slotSelectorCancelText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Chest Opening Modal Styles
  chestModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
    elevation: 50,
  },
  chestModalContent: {
    alignItems: 'center',
    width: '100%',
  },
  chestModalTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: '#FFD700',
    marginBottom: 40,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
    letterSpacing: 2,
  },
  chestVisual: {
    width: 200,
    height: 160,
    backgroundColor: '#5D4037', // Brown
    borderRadius: 20,
    borderWidth: 4,
    borderColor: '#8D6E63',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 20,
  },
  chestTapText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    opacity: 0.8,
    marginTop: 20,
  },
  rewardsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    padding: 20,
  },
  rewardRevealContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginVertical: 30,
  },
  rewardItemLarge: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardIconLarge: {
    fontSize: 80,
    marginBottom: 10,
  },
  rewardValueLarge: {
    color: '#fff',
    fontSize: 32,
    fontWeight: '900',
    textShadowColor: '#000',
    textShadowRadius: 4,
  },
  rewardLabelLarge: {
    color: '#FFD700',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 5,
  },
  cardCountBadge: {
    backgroundColor: '#34495e',
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 15,
    marginTop: 10,
    borderWidth: 2,
    borderColor: '#fff',
  },
  cardCountText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '900',
  },
  itemCountBadge: {
    position: 'absolute',
    top: -20,
    right: 40,
    backgroundColor: '#e74c3c',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#fff',
    elevation: 10,
    zIndex: 100,
  },
  itemCountText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '900',
  },
  closeChestButton: {
    marginTop: 40,
    backgroundColor: '#F1C40F',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 30,
    borderBottomWidth: 5,
    borderBottomColor: '#c29d0b',
  },
  closeChestButtonText: {
    color: '#3e2723',
    fontSize: 20,
    fontWeight: '900',
  },
  chestOpenText: {
    color: '#2ecc71',
    fontWeight: '900',
    fontSize: 10,
    textShadowColor: 'black',
    textShadowRadius: 1,
  },
  chestLockedText: {
    color: '#7f8c8d',
    fontWeight: 'bold',
    fontSize: 10,
  },
});

export default styles;
