"""Accurate visual descriptions for every card, used by gen_card_art.py (so the image model doesn't guess from the name)."""
DESC = {
 # troops
 'knight': "a sturdy human knight with a big brown mustache, a plain steel helmet with a nose guard, blue-grey armor, a short sword and a small round shield",
 'archers': "two young women archers with pink hair and green hooded cloaks, each drawing a wooden bow, dynamic stance side by side",
 'giant': "a huge muscular bald orange-skinned giant with a thick brown beard, bare chest, brown leather straps and wrist cuffs, tiny dark eyes, enormous fists",
 'mini_pekka': "a small armored robot-knight with a dark blue metal body, a horned helmet with glowing blue eyes, and a big steel sword",
 'spear_goblins': "three small green goblins with pointy ears each holding a long wooden spear, mischievous grins, leather shoulder straps",
 'musketeer': "a woman musketeer with a purple tricorn hat, a long brown coat and a long flintlock musket, confident stance",
 'baby_dragon': "a cute chubby green baby dragon with small wings, big eyes and a tiny puff of fire from its nose, flying",
 'cannon': "a small stone-and-wood defensive cannon on wheels aimed forward, iron barrel",
 'barbarians': "five blond barbarians with horned helmets, big blond mustaches, tan tunics and short swords, charging together",
 'skeleton_army': "a huge swarm of tiny white skeletons with helmets running together, spooky purple glow",
 'skeletons': "three small cartoon skeletons with grinning skulls, rusty swords and shields",
 'valkyrie': "a tall red-haired warrior woman in a green-and-red outfit with a horned helmet wielding a huge double-headed axe, spinning",
 'minions': "three small blue flying demon creatures with grey-blue skin, small wings and sharp claws, grinning",
 'minion_horde': "six small blue flying demon creatures with wings and claws swooping together",
 'witch': "a skeletal-faced witch in a dark purple robe and tall pointed hat with a skull-topped staff, summoning tiny skeletons",
 'hog_rider': "a muscular shirtless MAN with a blond mohawk riding on top of a pink HOG (pig) and swinging a golden war hammer; the man sits on the pig's back, the pig has tusks and charges forward",
 'prince': "a prince in gold-and-blue armor with a plumed helmet charging forward on a brown pony, holding a long lance",
 'tesla': "a blue-and-gold Tesla coil tower with crackling electricity at the top, sitting in a small stone base",
 'wizard': "a young blond wizard with a small mustache and goatee wearing a red-orange and purple wizard outfit, throwing a fireball",
 'tombstone': "a stone tombstone with a skull on top, cracks, a purple flame and tiny skeletons climbing out",
 'sword_goblins': "three small green goblins with pointy ears, each holding a short dagger-sword, mischievous grins",
 'ice_wizard': "a young wizard with white-blue hair wearing a fur-trimmed blue coat, holding a frosty staff, snow swirling",
 'lava_hound': "a giant flying fiery red-orange hound made of lava rock with a glowing mouth, smaller lava pups around it",
 'royal_hogs': "four pink war hogs with tusks wearing royal red-and-gold saddle blankets, charging",
 'miner': "a short stocky miner with a yellow hard hat with a lamp, a shovel and pickaxe, popping out of the ground",
 'goblin_cage': "a wooden cage holding an angry goblin brawler, with a lock and chains",
 'goblin_giant': "a huge green goblin carrying two small spear goblins on his back, big angry face, leather armor",
 'three_musketeers': "three musketeers with purple hats and long coats aiming muskets, standing in a triangle",
 'royal_giant': "a large giant with a royal red cape and a huge hand cannon, brown beard and a gold crown-shaped helmet",
 'dark_prince': "a dark knight prince with black-and-purple armor, a spiked shield and a large spiked mace, helmet with a purple plume",
 'elite_barbarians': "two huge muscular elite barbarians with blond mohawks and horned black helmets, huge swords, fierce roaring faces",
 'golem': "a massive brown stone golem with glowing orange cracks, big blocky fists and tiny head",
 'pekka': "a huge dark-grey armored robot-knight with a horned helmet, glowing blue visor eyes and a big dark steel sword",
 'mega_knight': "a giant armored knight with a big steel helmet, huge shoulders, two giant maces, jumping down with a shockwave",
 'electro_wizard': "a young wizard with spiky blond-blue hair and blue electric aura wearing a blue-and-yellow jacket, shooting lightning from both hands",
 'fire_spirit': "a TINY chibi fire spirit: a small round orange flame creature with big cute eyes, little arms and feet, a flame tuft on top, smiling mischievously",
 'ice_spirit': "a TINY chibi ice spirit: a small cute round light-blue ice creature with big sparkly eyes, tiny arms and feet, snowflake spikes on its head, smiling",
 'electro_spirit': "a TINY chibi electro spirit: a small cute round yellow-blue creature with big eyes and little sparks and lightning on its head",
 'heal_spirit': "a TINY chibi healing spirit: a small cute round pink-white creature with big eyes, little arms and feet, hearts and green sparkles",
 'bomber': "a small skeleton wearing a blue cap and a bomb-belt, holding a lit round black bomb",
 'furnace': "a small red-orange stone furnace creature with a glowing fire inside, spitting fire sparks",
 'spirit_empress': "a graceful empress in white and pink robes with large spirit wings, surrounded by glowing fox-spirit flames",
 'lumberjack': "a bearded lumberjack with a red plaid shirt, a wool hat and a big axe, angry",
 'guards': "three skeleton guards wearing helmets and carrying shields and small spears",
 'bats': "five small cute purple bats with big ears and fangs, flying",
 'ram_rider': "a viking woman riding a large charging ram, holding a bola/snare rope, ram with big curved horns",
 'battle_healer': "a woman healer in white-and-gold armor with a green glowing aura, a mace, healing allies",
 'skeleton_barrel': "a wooden barrel marked with a skull floating in the air held up by red balloons, little skeletons inside",
 'ice_golem': "a small stout golem made of blue ice crystals with white snow patches, glowing cold eyes",
 'mega_minion': "a bigger armored flying minion with a stone-grey armor shell and big fists, blue-grey skin, flying",
 'dart_goblin': "a small green goblin with a long blowgun shooting darts, tribal outfit, leaf skirt",
 'princess': "a blond princess with a long braid and a golden crown, wearing a white-and-blue dress, drawing a bow and shooting a flaming arrow",
 'bandit': "a masked thief with a red mask, brown hood and cape, dashing with two daggers",
 'battle_ram': "a big wooden battering ram with an iron ram's head, carried at a run by two barbarians with blond hair and horned helmets",
 'balloon': "a big round red hot-air balloon with a skull on it carrying a bomb, a grinning skull pilot in a basket",
 'hunter': "a young man hunter in a brown hat with a feather and a green coat, holding a big double-barrel shotgun",
 'electro_giant': "a huge giant with blue-tinted skin, an electric Tesla-coil backpack, electric blue sparks and arcs",
 'night_witch': "a dark witch in a long black-and-purple cloak with glowing eyes, a staff, with bats circling her",
 'inferno_dragon': "a red-orange dragon with a glowing flame beam from its mouth, wings spread, flying",
 'elixir_golem': "a golem made of pink-purple elixir blobs, stout body with big round fists, glowing elixir inside",
 'firecracker': "a young woman with red hair and goggles holding a huge firecracker rocket launcher, firing sparks",
 'giant_skeleton': "a giant skeleton with a big round bomb strapped to his back, wearing a small cap, huge bones",
 'electro_dragon': "a blue electric dragon with lightning crackling between its wings, flying",
 'magic_archer': "a young archer with blue hair in a blue-white hooded outfit, drawing a huge glowing blue magic bow with a glowing arrow",
 'royal_ghost': "a ghost knight with a cloak and a royal blue cape, floating pale-blue ghostly spirit holding a sword",
 'sparky': "a small thick tank robot with a big electric cannon on its back and sparks, goggles",
 'mother_witch': "an old witch with a hooked nose in a dark robe and pointed hat, holding a cursed staff with a magical pig sitting nearby",
 'bomb_tower': "a round stone tower with a cannon barrel on top that launches bombs, round black bombs next to it",
 'mortar': "a short stone mortar cannon that fires bombs in a high arc, bomb loaded",
 'x_bow': "a large wooden crossbow tower with a large drawn string and arrows, on a stone base",
 'goblin_hut': "a small wooden hut with a thatched roof and a green goblin peeking out, spawning goblins",
 'barbarian_hut': "a wooden barbarian hut with a pointed log roof, fire and horned decorations",
 'elixir_collector': "a pink elixir pump with a glass tank full of glowing pink elixir and pipes",
 'inferno_tower': "a dark stone tower with a glowing orange-red lava core shooting a flame beam, chains",
 'flying_machine': "a small flying wooden machine with propellers and a goblin pilot and a cannon",
 'wall_breakers': "two small skeleton demolition fighters with a barrel bomb strapped on and white helmets, running",
 'skeleton_dragons': "two small skeleton dragons with bony wings, breathing small fire, flying",
 'bowler': "a big blue-skinned bowler with a viking beard rolling a huge boulder",
 'executioner': "a muscular man with a hooded mask and a huge double-bladed axe that he throws like a boomerang",
 'zappies': "three small robot Zappies with electric orbs for hands, zapping, yellow-blue robots",
 'rascals': "a rascal boy with a slingshot and two girl rascals with slingshots, mischievous grins",
 'royal_recruits': "seven royal recruit soldiers with blue helmets and big square shields and spears, lined up",
 'cannon_cart': "a wooden cart with a large cannon on it and a shield, rolling on wheels",
 'goblin_drill': "a green spiked drill machine digging out of the ground with a goblin driver",
 'phoenix': "a big firebird phoenix with fiery wings and glowing flame tail feathers, flying",
 'fisherman': "a fisherman with a big red beard, a yellow raincoat and a large fish-hook on a chain",
 'goblin_gang': "a group of five goblins: three small spear goblins and two sword goblins, grinning",
 'goblin_demolisher': "a green goblin demolisher with goggles and a red cap on a bomb-barrel launcher, bombs around",
 'goblin_machine': "a green goblin piloting a clanky mech with a rocket fist and a big cannon, steam and gears",
 'rune_giant': "a big giant with stone rune tattoos glowing blue on his skin, carrying runic stone plates",
 'suspicious_bush': "a leafy green bush with two eyes peeking out, a hidden tiny goblin inside",
 'berserker': "a wild muscular man with red hair, ragged beard and a pair of axes, shouting battle rage",
 'golden_knight': "a golden armored knight with a golden helmet and a long golden chain-sword, flashing dash",
 'skeleton_king': "a king skeleton in a big crown, black armor and a huge scythe/sword, glowing green souls",
 'archer_queen': "an archer queen with a purple cloak and a crown, short dark hair, a crossbow, a purple glowing aura",
 'monk': "a martial-arts monk in an orange robe with a shaved head and wooden beads, calm pose, a glowing palm strike",
 'mighty_miner': "a muscular miner with a hard hat and big drill-arm, glowing drill, lava rocks",
 'little_prince': "a young boy prince with a small crown, a cape and a wooden toy sword, accompanied by a small guardian",
 'boss_bandit': "a huge masked boss thief with a red bandana, black coat, two daggers and gold coins",
 'goblinstein': "a green goblin mad scientist (Goblinstein) in a lab coat with wild hair next to a huge grumpy green monster with bolts in his neck, electric spark",
 # spells
 'fireball': "a big blazing fireball with a long flaming tail speeding down",
 'the_log': "a rolling wooden log with a cute carved face, rolling forward, knocking things back",
 'arrows': "a volley of many arrows raining down from the sky in a tight group",
 'zap': "a quick bright bolt of blue lightning striking the ground in a circle",
 'poison': "a swirling cloud of toxic green poison with bubbles and a skull-like swirl",
 'rocket': "a red rocket with fins diving down trailing flame and about to explode",
 'lightning': "three powerful bolts of lightning striking at once from a stormy sky",
 'mirror': "a magic round mirror with a silver frame reflecting a glowing card",
 'goblin_barrel': "a wooden barrel with a green goblin face flying through the air, goblins ready to jump out",
 'earthquake': "the ground cracking and breaking apart with rubble and dust in a circle",
 'graveyard': "a graveyard with many skeleton hands bursting out of the ground at night, tombstones and fog",
 'clone': "a magic spell making a glowing blue copy of a small warrior next to the original",
 'freeze': "a burst of ice and snow freezing everything, frozen blue crystals",
 'rage': "a swirling purple rage potion/spell with a glowing aura and speed lines",
 'snowball': "a big rolling snowball with icy white-blue sparkles",
 'barb_barrel': "a wooden barrel with a barbarian face rolling and bursting",
 'royal_delivery': "a wooden royal crate falling from the sky with a parachute and a recruit inside",
 'tornado': "a swirling gray-blue tornado funnel pulling things in",
 'goblin_curse': "a green-purple cursed goblin mark spell with skulls and wisps",
 'void': "a dark purple void portal sucking in light with black energy tendrils",
 'vines': "thick green vines bursting out of the ground and wrapping around",
 'ronin': "a lone samurai ronin: a masked swordsman in a wide straw hat with a red scarf, dark armor and a long glowing katana held low in a parrying stance",
 'minion_giant': "a big chubby green flying minion giant with small wings, a wide mouth spitting green toxin, floating menacingly",
}
