class_name Chaos
extends RefCounted
## CHAOS mode: like the real Clash Royale event, every card has three modifiers (Common / Rare / Epic, data/chaos_mods.json, generated by
## tools/chaos/gen_chaos_mods.py). About every 40 s of battle time (first pick at 15 s, so five picks fit in a normal match) the game pauses and both sides pick one of two offered modifiers; the tier
## climbs as the match goes on (2x Common, 2x Rare, 1x Epic), each card can be upgraded once per match.
## A modifier is a bag of effect primitives ("fx"). Stat primitives are baked into the battle-local copy of the card by apply(); the
## behavioural ones are stored in card["cx"] (copied onto every unit made from the card) and run from the hooks below.

const INTERVAL := 40.0
const FIRST_AT := 15.0
const MAX_PICKS := 5
const TIERS := ["common", "rare", "epic"]
const DMG_KEYS := ["damage", "spawnDamage", "deathDamage", "shockDamage"]
const RADIUS_KEYS := ["radius", "splashRadius", "deathRadius", "spawnDamageRadius", "healRadius"]
## spells that cast_spell() handles itself; everything else lands through spell_land() as an instant area hit
const DIRECT_SPELLS := ["lightning", "zap", "the_log", "barb_barrel", "poison", "earthquake", "graveyard", "clone", "freeze", "rage",
	"goblin_curse", "void", "vines", "tornado", "royal_delivery", "goblin_barrel"]
const ROLLING := ["the_log", "barb_barrel"]
const SPELL_DEFAULT_DUR := {"vines": 4.0, "goblin_curse": 6.0, "void": 5.0, "tornado": 1.0, "poison": 8.0, "freeze": 4.0, "rage": 7.0, "clone": 10.0}

static var DATA: Dictionary = {}     # card id -> [common, rare, epic] each {tier, name, desc, fx, src}
static var _loaded := false

var sim: Sim
var picks := [0, 0]
var upgraded: Array = [{}, {}]       # per player: card id -> tier picked
var next_at := FIRST_AT
var options: Array = []              # current offers for the human
var waiting := false
var elapsed := 0.0                   # battle seconds (advances only while the sim runs)
var pending: Array = []              # delayed spell casts {at, id, ds, rs, x, y, opp}

func _init(s: Sim) -> void:
	sim = s
	ensure()

static func ensure() -> void:
	if _loaded:
		return
	_loaded = true
	var f := FileAccess.open("res://data/chaos_mods.json", FileAccess.READ)
	DATA = JSON.parse_string(f.get_as_text())

static func mod_for(card_id: String, tier: String) -> Dictionary:
	ensure()
	if not DATA.has(card_id):
		return {}
	var idx := TIERS.find(tier)
	return DATA[card_id][idx] if idx >= 0 else {}

# ---- applying a modifier to a battle-local card ----------------------------------------------
static func apply(card: Dictionary, mod: Dictionary) -> void:
	if mod.is_empty():
		return
	var fx: Dictionary = mod["fx"]
	var cx: Dictionary = card.get("cx", {})
	var t := str(card.get("type", "ground"))
	for k in fx:
		var v: Variant = fx[k]
		match k:
			"hp": card["hp"] = floorf(float(Sim._v(card, "hp", 0)) * float(v))
			"dmg":
				for dk in DMG_KEYS:
					if card.get(dk) != null:
						card[dk] = floorf(float(card[dk]) * float(v))
			"range": card["range"] = float(card["range"]) * float(v)
			"speed": card["speed"] = float(card["speed"]) * float(v)
			"hit": card["attackSpeed"] = float(card["attackSpeed"]) / float(v)
			"cost": card["cost"] = maxi(1, int(card["cost"]) + int(v))
			"count":
				if t == "spell":
					if card.get("spawnCount") != null:
						card["spawnCount"] = int(card["spawnCount"]) + int(v)
					card["count"] = int(Sim._v(card, "count", 1)) + int(v)
				else:
					card["count"] = int(Sim._v(card, "count", 1)) + int(v)
			"radius":
				var hit_any := false
				for rk in RADIUS_KEYS:
					if card.get(rk) != null:
						card[rk] = float(card[rk]) * float(v)
						hit_any = true
				if not hit_any and card.get("splash", false):
					card["splashRadius"] = 50.0 * float(v)
			"dur":
				if t == "spell":
					var cid := str(card["id"])
					if cid == "freeze":
						card["freezeDuration"] = float(Sim._v(card, "freezeDuration", 4.0)) * float(v)
					elif cid == "rage":
						card["rageDuration"] = float(Sim._v(card, "rageDuration", 7.0)) * float(v)
					elif cid == "clone":
						card["cloneDuration"] = float(Sim._v(card, "cloneDuration", 10.0)) * float(v)
					else:
						card["duration"] = float(Sim._v(card, "duration", SPELL_DEFAULT_DUR.get(cid, 4.0))) * float(v)
				elif card.get("lifetime") != null:
					card["lifetime"] = float(card["lifetime"]) * float(v)
			"rate": card["spawnRate"] = float(card["spawnRate"]) / float(v)
			"shield":
				card["hasShield"] = true
				card["shieldHp"] = float(Sim._v(card, "shieldHp", 0)) + float(v)
			"scale": card["chaosScale"] = float(Sim._v(card, "chaosScale", 1.0)) * float(v)
			"kb": card["knockback"] = float(Sim._v(card, "knockback", 0)) + float(v)
			"stun": card["stun"] = maxf(float(Sim._v(card, "stun", 0)), float(v))
			"slow":
				card["slow"] = float(v[0])
				card["slowDuration"] = float(v[1])
			"splash":
				card["splash"] = true
				card["splashRadius"] = maxf(float(Sim._v(card, "splashRadius", 0)), float(v))
			"charge": card["charge"] = true
			"noKB": card["noKnockback"] = true
			"hidden": card["hidden"] = true
			"jumps": card["jumps"] = true
			"pierce":
				card["pierce"] = true
				card["projectileTravelDistance"] = maxf(float(Sim._v(card, "projectileTravelDistance", 0)), float(Sim._v(card, "range", 100)) * 1.4)
			"boom":
				card["deathDamage"] = maxf(float(Sim._v(card, "deathDamage", 0)), maxf(150.0, floorf(float(Sim._v(card, "damage", 100)) * float(v[0]))))
				card["deathRadius"] = maxf(float(Sim._v(card, "deathRadius", 0)), float(v[1]))
			"shock":
				card["shockRadius"] = float(Sim._v(card, "shockRadius", 50)) * float(v)
				card["shockDamage"] = float(Sim._v(card, "shockDamage", 100)) * float(v)
			"egg": card["eggDuration"] = float(card["eggDuration"]) * float(v)
			"freeze": card["freezeDuration"] = float(card["freezeDuration"]) + float(v)
			_:
				cx[k] = v
	if not cx.is_empty():
		card["cx"] = cx
	card["chaosTier"] = mod["tier"]
	card["chaosName"] = mod["name"]

# ---- offers ----------------------------------------------------------------------------------
func tier_for(pick_index: int) -> String:
	return "common" if pick_index < 2 else ("rare" if pick_index < 4 else "epic")

## Two offers: {card, tier, name, desc, src}
func make_offers(pi: int) -> Array:
	var tier := tier_for(int(picks[pi]))
	var pool: Array = []
	var seen := {}
	for c in sim.players[pi]["deck"]:
		var cid := str(c["id"])
		if seen.has(cid) or upgraded[pi].has(cid) or not DATA.has(cid):
			continue
		seen[cid] = true
		pool.append(cid)
	pool.shuffle()
	var out: Array = []
	for cid in pool.slice(0, 2):
		var m := mod_for(cid, tier)
		out.append({"card": cid, "tier": tier, "name": m["name"], "desc": m["desc"], "src": m.get("src", false)})
	return out

func choose(pi: int, offer: Dictionary) -> void:
	var cid := str(offer["card"])
	var m := mod_for(cid, str(offer["tier"]))
	for c in sim.players[pi]["deck"]:
		if c["id"] == cid:
			apply(c, m)
	upgraded[pi][cid] = offer["tier"]
	sim.fx.append({"t": "alert", "msg": "%s: %s" % [("YOU" if pi == 0 else "ENEMY"), str(offer["name"]).to_upper()]})
	picks[pi] += 1

func ai_pick() -> void:
	var offers := make_offers(1)
	if offers.is_empty():
		return
	choose(1, offers[randi() % offers.size()])

## Called every frame by the battle; returns true when the human must choose.
func update_clock() -> bool:
	elapsed = sim.now / 1000.0
	if not waiting and elapsed >= next_at and int(picks[0]) < MAX_PICKS and sim.game_over == "":
		next_at += INTERVAL
		ai_pick()
		options = make_offers(0)
		if options.is_empty():
			return false
		waiting = true
		return true
	return false

# ---- helpers ---------------------------------------------------------------------------------
func _side(opp: bool) -> int:
	return 1 if opp else 0

func spawn_cards(id: String, n: int, x: float, y: float, opp: bool) -> void:
	var c := CardDB.get_card(id)
	if c.is_empty():
		return
	var cnt := mini(24, maxi(1, int(Sim._v(c, "count", 1))) * n)
	var lane := "LEFT" if x < Sim.W / 2.0 else "RIGHT"
	for i in cnt:
		var a: float = sim.rng.randf() * TAU
		var rr: float = (12.0 + sim.rng.randf() * 16.0) if cnt > 1 else 0.0
		var u := sim.make_unit(c, clampf(x + cos(a) * rr, 20.0, Sim.W - 20.0), clampf(y + sin(a) * rr, 20.0, Sim.H - 20.0), opp, lane)
		sim.units.append(u)
		sim.mech.on_spawn(u)
	sim.fx.append({"t": "spell", "x": x, "y": y, "r": 26.0, "kind": "clone"})

func cast(id: String, ds: float, rs: float, x: float, y: float, opp: bool) -> void:
	var base := CardDB.get_card(id)
	if base.is_empty():
		return
	var c: Dictionary = base.duplicate(true)
	c.erase("cx")
	for dk in DMG_KEYS:
		if c.get(dk) != null:
			c[dk] = floorf(float(c[dk]) * ds)
	if c.get("radius") != null:
		c["radius"] = float(c["radius"]) * rs
	x = clampf(x, 10.0, Sim.W - 10.0)
	y = clampf(y, 10.0, Sim.H - 10.0)
	if id in DIRECT_SPELLS:
		sim.mech.cast_spell(c, x, y, opp)
	else:
		sim.mech.spell_land({"card": c, "targetX": x, "targetY": y, "opp": opp})

func _nearest_enemy(x: float, y: float, opp: bool, maxd: float) -> Variant:
	var best: Variant = null
	var bd := maxd
	for e in sim.units:
		if e["opp"] == opp or e["hp"] <= 0 or sim._is_hidden(e):
			continue
		var d := Sim.dist(e["x"], e["y"], x, y)
		if d < bd:
			bd = d
			best = e
	return best

func _enemies_in(x: float, y: float, r: float, opp: bool) -> Array:
	var out: Array = []
	for e in sim.units:
		if e["opp"] != opp and e["hp"] > 0 and e["type"] != "building" and Sim.dist(e["x"], e["y"], x, y) <= r:
			out.append(e)
	return out

func _add_elixir(opp: bool, n: float) -> void:
	var p: Dictionary = sim.players[_side(opp)]
	p["elixir"] = minf(10.0, float(p["elixir"]) + n)
	if not opp:
		sim.fx.append({"t": "alert", "msg": "+%d ELIXIR" % int(n)})

func _queue(id: String, ds: float, rs: float, delay: float, x: float, y: float, opp: bool) -> void:
	pending.append({"at": sim.now + maxf(0.05, delay) * 1000.0, "id": id, "ds": ds, "rs": rs, "x": x, "y": y, "opp": opp})

# ---- deploy / cast hooks ---------------------------------------------------------------------
## Called by Sim.deploy_card after a troop/building card was placed.
func on_deploy(card: Dictionary, x: float, y: float, opp: bool, spawned: Array) -> void:
	var cx: Dictionary = card.get("cx", {})
	if cx.is_empty():
		return
	if cx.has("spawnDeploy"):
		for e in cx["spawnDeploy"]:
			spawn_cards(str(e[0]), int(e[1]), x, y + (-24.0 if opp else 24.0), opp)
	if cx.has("castDeploy"):
		for e in cx["castDeploy"]:
			var tgt: Variant = _nearest_enemy(x, y, opp, 220.0)
			var tx := x
			var ty := y
			if not (str(e[0]) in ROLLING):
				if tgt != null:
					tx = tgt["x"]
					ty = tgt["y"]
				else:
					ty = y + (60.0 if opp else -60.0)
			cast(str(e[0]), float(e[1]), float(e[2]), tx, ty, opp)
	if cx.has("blast"):
		_blast(x, y, opp, cx["blast"])
	if cx.has("elixirDeploy"):
		_add_elixir(opp, float(cx["elixirDeploy"]))
	if cx.has("rageSelf"):
		for u in spawned:
			u["rageUntil"] = sim.now + float(cx["rageSelf"]) * 1000.0
			u["rageBoost"] = 0.35

func _blast(x: float, y: float, opp: bool, b: Array) -> void:
	var ev := {"x": x, "y": y, "r": float(b[0]), "dmg": float(b[1]), "opp": opp, "skip_id": -1, "tower_factor": 1.0, "attacker": -1,
		"ground_only": false, "tower_hit": true, "stun": float(b[2]), "knockback": float(b[3])}
	var out: Array = []
	sim._apply_splash(ev, out)
	sim._apply_damage(out)
	sim.fx.append({"t": "spell", "x": x, "y": y, "r": float(b[0]), "kind": "earthquake"})

## Called by Mechanics.cast_spell for a spell card that carries chaos effects.
func on_cast(card: Dictionary, x: float, y: float, opp: bool) -> void:
	var cx: Dictionary = card.get("cx", {})
	if cx.is_empty():
		return
	if cx.has("spawnDeploy"):
		for e in cx["spawnDeploy"]:
			spawn_cards(str(e[0]), int(e[1]), x, y, opp)
	if cx.has("weaken"):
		var w: Array = cx["weaken"]
		for e in _enemies_in(x, y, float(Sim._v(card, "radius", 40)), opp):
			e["weakUntil"] = sim.now + float(w[1]) * 1000.0
			e["weakPct"] = float(w[0])
	if cx.has("castAlso"):
		for a in cx["castAlso"]:
			var shift := float(a[4]) if a.size() > 4 else 0.0
			_queue(str(a[0]), float(a[1]), float(a[2]), float(a[3]), x, y + shift * (-1.0 if opp else 1.0), opp)

# ---- per-tick behaviours ---------------------------------------------------------------------
func _due(u: Dictionary, key: String, every_ms: float) -> bool:
	var t: Dictionary = u.get("cxT", {})
	var last: float = float(t.get(key, u["spawnTime"]))
	if sim.now - last >= every_ms:
		t[key] = sim.now
		u["cxT"] = t
		return true
	return false

func tick() -> void:
	var now := sim.now
	if not pending.is_empty():
		var rest: Array = []
		for p in pending:
			if now >= float(p["at"]):
				cast(str(p["id"]), float(p["ds"]), float(p["rs"]), float(p["x"]), float(p["y"]), bool(p["opp"]))
			else:
				rest.append(p)
		pending = rest
	for u in sim.units.duplicate():
		if u["hp"] <= 0 or not u.has("cx") or u.get("spawnTime", 0.0) > now:
			continue
		var cx: Dictionary = u["cx"]
		if cx.has("spawnEvery"):
			var e: Array = cx["spawnEvery"]
			if _due(u, "spawnEvery", float(e[2]) * 1000.0):
				spawn_cards(str(e[0]), int(e[1]), u["x"], u["y"] + (-20.0 if u["opp"] else 20.0), u["opp"])
		if cx.has("castEvery"):
			var e2: Array = cx["castEvery"]
			if _due(u, "castEvery", float(e2[1]) * 1000.0):
				var tgt: Variant = _nearest_enemy(u["x"], u["y"], u["opp"], 170.0)
				if tgt != null:
					cast(str(e2[0]), float(e2[2]), float(e2[3]), tgt["x"], tgt["y"], u["opp"])
		if cx.has("elixirEvery"):
			var e3: Array = cx["elixirEvery"]
			if _due(u, "elixirEvery", float(e3[1]) * 1000.0):
				_add_elixir(u["opp"], float(e3[0]))
				sim.fx.append({"t": "elixir", "x": u["x"], "y": u["y"]})
		if cx.has("pulse"):
			var pl: Array = cx["pulse"]
			if _due(u, "pulse", float(pl[1]) * 1000.0):
				_pulse(u, str(pl[0]), float(pl[2]), float(pl[3]))
		if cx.has("blink"):
			var b: Array = cx["blink"]
			if _due(u, "blink", float(b[0]) * 1000.0):
				var fwd := float(b[1]) * (1.0 if u["opp"] else -1.0)
				sim.fx.append({"t": "spell", "x": u["x"], "y": u["y"], "r": 30.0, "kind": "freeze"})
				u["y"] = clampf(u["y"] + fwd, 30.0, Sim.H - 30.0)
				sim.fx.append({"t": "spell", "x": u["x"], "y": u["y"], "r": 30.0, "kind": "zap"})

func _pulse(u: Dictionary, kind: String, r: float, val: float) -> void:
	var now := sim.now
	match kind:
		"pull", "push":
			for e in _enemies_in(u["x"], u["y"], r, u["opp"]):
				var d := Sim.dist(e["x"], e["y"], u["x"], u["y"])
				if d > 6.0:
					var s := minf(d - 4.0, val) * (1.0 if kind == "pull" else -1.0)
					e["x"] = clampf(e["x"] + (u["x"] - e["x"]) / d * s, 10.0, Sim.W - 10.0)
					e["y"] = clampf(e["y"] + (u["y"] - e["y"]) / d * s, 10.0, Sim.H - 10.0)
			sim.fx.append({"t": "spell", "x": u["x"], "y": u["y"], "r": r, "kind": "tornado"})
		"stun":
			for e in _enemies_in(u["x"], u["y"], r, u["opp"]):
				e["stunUntil"] = maxf(e["stunUntil"], now + val * 1000.0)
			sim.fx.append({"t": "spell", "x": u["x"], "y": u["y"], "r": r, "kind": "zap"})
		"slow":
			for e in _enemies_in(u["x"], u["y"], r, u["opp"]):
				e["slowUntil"] = now + 2000.0
				e["slowAmount"] = val
			sim.fx.append({"t": "spell", "x": u["x"], "y": u["y"], "r": r, "kind": "freeze"})
		"dmg":
			for e in _enemies_in(u["x"], u["y"], r, u["opp"]):
				sim._apply_damage([{"id": e["id"], "dmg": val, "attacker": u["id"]}])
			sim.fx.append({"t": "splash", "x": u["x"], "y": u["y"], "r": r})
		"heal", "rage", "shield":
			for a in sim.units:
				if a["opp"] != u["opp"] or a["hp"] <= 0 or Sim.dist(a["x"], a["y"], u["x"], u["y"]) > r:
					continue
				if kind == "heal":
					a["hp"] = minf(float(a["maxHp"]), float(a["hp"]) + val)
				elif kind == "rage":
					a["rageUntil"] = maxf(float(Sim._v(a, "rageUntil", 0.0)), now + 3000.0)
					a["rageBoost"] = 0.35
				elif a["type"] != "building":
					a["currentShieldHp"] = minf(float(a["currentShieldHp"]) + val, val * 2.0)
			sim.fx.append({"t": "splash", "x": u["x"], "y": u["y"], "r": r})

# ---- attack / death hooks --------------------------------------------------------------------
## Called from Mechanics.on_attack for every attack of a unit that carries chaos effects.
func on_attack(u: Dictionary, target: Dictionary, damage: float) -> void:
	var cx: Dictionary = u.get("cx", {})
	if cx.is_empty():
		return
	var is_tower: bool = target.has("isTower")
	if cx.has("lifesteal"):
		u["hp"] = minf(float(u["maxHp"]), float(u["hp"]) + damage * float(cx["lifesteal"]))
	if cx.has("zap") and not is_tower:
		var z: Array = cx["zap"]
		var chained: Array = [target]
		for i in int(z[0]):
			var last: Dictionary = chained[chained.size() - 1]
			var best: Variant = null
			var bd := 85.0
			for e in sim.units:
				if e["opp"] == u["opp"] or e["hp"] <= 0 or chained.has(e):
					continue
				var d := Sim.dist(e["x"], e["y"], last["x"], last["y"])
				if d < bd:
					bd = d
					best = e
			if best == null:
				break
			chained.append(best)
			sim._apply_damage([{"id": best["id"], "dmg": damage * float(z[1]), "attacker": u["id"], "stun": 0.2}])
			sim.fx.append({"t": "bolt", "x": best["x"], "y": best["y"]})
	if cx.has("weaken") and not is_tower:
		var w: Array = cx["weaken"]
		target["weakUntil"] = sim.now + float(w[1]) * 1000.0
		target["weakPct"] = float(w[0])
	var ctr: Dictionary = u.get("cxC", {})
	if cx.has("spawnHit"):
		var s: Array = cx["spawnHit"]
		ctr["spawnHit"] = int(ctr.get("spawnHit", 0)) + 1
		if int(ctr["spawnHit"]) % maxi(1, int(s[2])) == 0:
			spawn_cards(str(s[0]), int(s[1]), u["x"], u["y"] + (-16.0 if u["opp"] else 16.0), u["opp"])
	if cx.has("castHit"):
		var ch: Array = cx["castHit"]
		ctr["castHit"] = int(ctr.get("castHit", 0)) + 1
		if int(ctr["castHit"]) % maxi(1, int(ch[1])) == 0:
			cast(str(ch[0]), float(ch[2]), float(ch[3]), target["x"], target["y"], u["opp"])
	u["cxC"] = ctr

## Called from Sim._on_death for every unit that dies.
func on_death(d: Dictionary) -> void:
	var cx: Dictionary = d.get("cx", {})
	if cx.is_empty():
		return
	if cx.has("spawnDeath"):
		for e in cx["spawnDeath"]:
			spawn_cards(str(e[0]), int(e[1]), d["x"], d["y"], d["opp"])
	if cx.has("castDeath"):
		for e in cx["castDeath"]:
			cast(str(e[0]), float(e[1]), float(e[2]), d["x"], d["y"], d["opp"])
	if cx.has("elixirDeath"):
		_add_elixir(d["opp"], float(cx["elixirDeath"]))

## Called by Sim before dead units are removed: "returns once with X% HP".
func revive(u: Dictionary) -> bool:
	var cx: Dictionary = u.get("cx", {})
	if cx.has("revive") and not u.get("revived", false):
		u["revived"] = true
		u["hp"] = maxf(1.0, floorf(float(u["maxHp"]) * float(cx["revive"])))
		u["stunUntil"] = maxf(u["stunUntil"], sim.now + 600.0)
		sim.fx.append({"t": "spell", "x": u["x"], "y": u["y"], "r": 40.0, "kind": "fireball"})
		return true
	return false
